services:
  - type: web
    name: dagi-bingo
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: MONGODB_URI
        placeholder: "mongodb+srv://<username>:<password>@cluster0.mongodb.net/dagibingo"
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CHAPA_PUBLIC_KEY
        value: CHAPUBK_TEST-F8wVF0CiDxcc6xAut5vm1oFKM4VCVCG9
      - key: CHAPA_SECRET_KEY
        value: CHASECK_TEST-EzF8SkHTiEva3p8xXcwKREFNpIHCq5hu
      - key: CHAPA_API_URL
        value: https://api.chapa.co/v1
      - key: GAME_MODE
        value: DEMO
